### ISSUE TITLE
PayPal contribute link goes to generic paypal.com

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-Desktop#18]
Two paypal buttons in the app:
* Clicking "Give back!" in the lower left hand corner, then pressing the "Contribute with PayPal"
* About Page > Contribute section

This works in the online app, and uses a form submit to launch a webpage. 
 But in the Electron app, the webpage resolves to the generic paypal site https://www.paypal.com/us/home.

I'll look into if we can convert this to a generic link instead of a form submit (the other links that launch webpages work within the Electron app).

**Comment by kethinov** [comment]
I would recommend checking out PayPal's somewhat new "paypal.me" feature which makes these kinds of integrations much easier. That way all we'd need to do is add a simple external link to the electron app, like this: https://github.com/kethinov/BubblePainter/blob/32997b30d9a0e3b352be0b4522be22434c1eb414/app/main.html#L78

**Comment by mattlag** [comment]
I changed this to a simple link, instead of a form > submit. I'll look into paypal.me, though, thanks.
