### ISSUE TITLE
Native menus source "About [app name]" from package.json "name" which creates problems

### ISSUE THREAD

**Issue by kethinov** [glyphr-studio/Glyphr-Studio-Desktop#25]
![screen shot 2017-12-31 at 12 48 58 am](https://user-images.githubusercontent.com/419567/34459670-7162618e-edc4-11e7-943f-b27721657b30.png)

Obviously we should want to change it from something other than "glyphr-studio-desktop" like "Glyphr Studio" instead but the build process sources it *directly* from the "name" field in package.json.

And what's worse is if you change the "name" field in package.json to something human readable, it totally breaks the build process. `npm i` stops working, other stuff breaks, it's a mess.

We need a way around this.

**Comment by Autre31415** [comment]
You can set a `"productName"` param in package.json to get a human readable name in the menus.
