### ISSUE TITLE
Help About is missing

### ISSUE THREAD

**Issue by peterennisrda** [glyphr-studio/Glyphr-Studio-Desktop#27]
I just downloaded the 64 bit Windows version. It looks very nice!
I wanted to check the version and compare with the current online system.
However, there is no Help/About option.
It is standard/common with Windows app.

**Comment by peterennisrda** [comment]
The option is available in the burger menu.
I am referring to the top File... menu

**Comment by kethinov** [comment]
Yeah, that's a good point. I implemented it for the Mac version (below) but not for the Linux or Windows versions.

![screen shot 2018-01-05 at 4 45 31 pm](https://user-images.githubusercontent.com/419567/34630015-53e2176c-f238-11e7-9828-d1b0acb35567.png)

![screen shot 2018-01-05 at 4 45 35 pm](https://user-images.githubusercontent.com/419567/34630018-576efdf0-f238-11e7-8845-4f54f822b488.png)

**Comment by kethinov** [comment]
Notably that is just for the desktop application build. The actual version of Glyphr Studio itself that is bundled with the desktop version is noted on the welcome screen:

![screen shot 2018-01-05 at 4 51 46 pm](https://user-images.githubusercontent.com/419567/34630121-dbffb55a-f238-11e7-9d5b-0b1782fabe0e.png)

**Comment by peterennisrda** [comment]
Correct. However, my experience of welcome screens is they create word blindness and
auto-click-thru :)

**Comment by kethinov** [comment]
Yeah. It seems like a proper about screen would surface both the desktop build version and the Glyphr version itself rather than burying them in two different places. Plus work on more than just one OS, haha.
