### ISSUE TITLE
Oops! Sorry

### ISSUE THREAD

**Issue by peterennisrda** [glyphr-studio/Glyphr-Studio-Desktop#28]
![capture1294](https://user-images.githubusercontent.com/1280523/34632551-faf6f8b2-f26d-11e7-9494-5a7f68fa0317.PNG)
![capture1293](https://user-images.githubusercontent.com/1280523/34632552-fb2177ae-f26d-11e7-9073-953dc8d63d32.PNG)

**Comment by kethinov** [comment]
@mattlag can you take care of this one

**Comment by mattlag** [comment]
Yeah, I had splurged on the super fancy .studio TLD... but after a year I reconsidered and I don't think it's worth it :-)
