### ISSUE TITLE
I can't Even Install

### ISSUE THREAD

**Issue by FrankRHarr** [glyphr-studio/Glyphr-Studio-Desktop#33]
Hi, I'm trying to download and install the program, but am continuously failing.  What should I be doing?

**Comment by kethinov** [comment]
There isn't really an "installation" step. You just unzip the zip file and run the executable. Are you getting some kind of error?

**Comment by FrankRHarr** [comment]
Yeah, I'm being told that:
"The procedure entry point SHGetPropertyStoreForWindow could not be located in the dynamic link library SHELL.dll." and then it stops working.

When I un-zipped the program, I got stuff all over the place and I'm wondering if I should have unzipped it to my program files.  I tend to run instal program on my desktop because they're easier to find there, and after I cleaned all the mess up, I put it in its own folder and ran it there.

I tried running it though GitBash, but when I got to the nmp i step I was told that command didn't exist.

I know I'm doing something wrong, but I have no idea what the hell it could be.

**Comment by kethinov** [comment]
Seems to work for me. Here's the procedure I tested with:

- Windows 10 x64 (latest patches)
- Download x64 or ia32 build
- Extract to a folder on the Desktop
- Open the exe in explorer

Anything different in your environment or procedure?

**Comment by FrankRHarr** [comment]
By the way, I've been using the online studio (it keeps crashing my browser) and I did what I needed to do and I can't use the file.  In anything.  At all.  It's strange.

**Comment by FrankRHarr** [comment]
I thought maybe that if I give the program its own folder in Program Files it would work, and nope, it still can't find the information.

**Comment by kethinov** [comment]
Sorry for the delay. GitHub wasn't notifying me of replies to this thread.

Only [Windows 7 and later are supported by Electron](https://electronjs.org/docs/tutorial/support#supported-platforms), the underlying framework which drives the desktop app.

**Comment by FrankRHarr** [comment]
Drat.  That would explain it.  Thank you.

By the way, could that have something to do with the problem I'm having with the online studio?  I'm having naming issues and when I try to save in my font folder from the studio, I get told I can't and when I try to copy and save from my downloads folder, I have problems getting my applications to see it.  And why does every typeface want to be called "MyFont-" something or other?  I can kind of progress, and I got one thing to work, but I have no idea what I did.

**Comment by kethinov** [comment]
What browser?

**Comment by FrankRHarr** [comment]
Firefox 52.8.1

**Comment by kethinov** [comment]
Are you able to upgrade to a new version and/or try it in another browser? Useful to know if it's exclusive to that browser/version.

**Comment by FrankRHarr** [comment]
It's the newest version they have.  Let me try in IE.

**Comment by kethinov** [comment]
The latest version of Firefox is 60. Looks like Mozilla [no longer supports Windows Vista](https://en.wikipedia.org/wiki/Firefox#Microsoft_Windows) though. I looked at Chrome and they also ended support for Vista some time ago.

**Comment by FrankRHarr** [comment]
Well, IE gets nothing and it looks like nothing else will work as it should.  Also, Chrome is horrible, I'm not touching that.

Thank you for your time, I appreciate it.  I'll keep trying, I may blunder into a solution like I did before.

**Comment by kethinov** [comment]
@mattlag you wouldn't happen to have a list somewhere of browsers/versions that are supported would you?

**Comment by mattlag** [comment]
For the most part, any of the most recent "modern" browsers should work.  It seems like we're talking about Vista... [File Writing functionality is not supported on FireFox 52](https://caniuse.com/#compare=firefox+52)

The biggest issue we run into with current browsers is actually the File Save functionality - sometimes Safari refuses to do that.  Besides that, we aren't using any advanced features... Canvas is the next most custom thing, which has been supported by basically everyone for many years now.

Technically we assume people are using the most recent version of their browser, we do no test matrix for past browser versions.  If your OS can support the latest version of a browser, Chrome, FireFox, and Edge should work, and we'll fix bugs for those.  Safari and IE and anything else is unsupported.


So, unfortunately @FrankRHarr you can try to install Chrome, see if that works... or upgrade your OS.

**Comment by FrankRHarr** [comment]
Thank you for you time, but I have found a way around the problem.

I studied web design briefly many years ago.  NEVER assume people are using the most up to date browsers or equipment, because there will always be people who don't.  That's not specificaly about this, it's just a general thing to keep in mind.
