### ISSUE TITLE
Linux installation questions

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-Desktop#37]
Forwarding an email from a user about installing on Linux.  I think if somebody can tell me the answers, I can answer him back in email... but number 2 and 3 may also be some work items to address.

=========

I'm trying Glyphr.studio Desktop (beta), that I find a light and
versatile tool, but I'v a lot of questions not always explained in a
clear and above all exhaustive way in the online guides. I'm using 64bit
Debian testing and LinuxMint.

1. To install Glyphr.studio is it enough to unpack the main archive?

2. Is there a icon to put the program in the Application Menu?

3. How is it possible to have the right localization?
I find the /locales directory and my system is set in Italian,
but Glyphr.studio is always in English. It's not a so big problem,
but I'd like to understand the way to configure it all.

**Comment by probonopd** [comment]
Before you can run an AppImage, you need to make it executable. This is a Linux security feature. There are three main ways to make an AppImage executable:

**1. With the GUI**

1. Open your file manager and browse to the location of the AppImage
2. Right-click on the AppImage and click the ‘Properties’ entry
3. Switch to the Permissions tab and
4. Click the ‘Allow executing file as program’ checkbox if you are using a Nautilus-based file manager (Files, Nemo, Caja), or click the ‘Is executable’ checkbox if you are using Dolphin, or change the ‘Execute’ drop down list to ‘Anyone’ if you are using PCManFM
5. Close the dialog
6. Double-click on the AppImage file to run

<img src='/uploads/appimage/original/1X/a4889c5cb8711d6845b58135080787d2f370af35.gif'>

**2. On the command line**

```
chmod a+x Some.AppImage
```

**3. Automatically with the optional appimaged daemon**

If you would like to have all AppImages be executable automatically, you can install the optional `appimaged` daemon. It will automatically add downloaded AppImages to the menu and make them executable for you. It can be downloaded from https://github.com/AppImage/AppImageKit/releases or installed from your distribution.
