### ISSUE TITLE
Can not launch latest AppImage

### ISSUE THREAD

**Issue by Symbian9** [glyphr-studio/Glyphr-Studio-Desktop#42]
**Build**: https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases/download/v0.5.1/Glyphr.Studio.0.5.1.AppImage

**System**: Linux (Debian 9.x, x86_64)

### Terminal output

```
$ ./Glyphr.Studio.0.5.1.AppImage
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_GlyphrRBTp6w/AppRun.
[6000:0513/052903.377745:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /var/tmp/.mount_GlyphrRBTp6w/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

Cast @probonopd

**Comment by probonopd** [comment]
Try running with `--no-sandbox`.

Reference:
https://github.com/johannesjo/super-productivity/issues/167

**Comment by probonopd** [comment]
Possibly related to https://github.com/electron/electron/issues/17972.

**Comment by thomasnordquist** [comment]
The initial comment provides a workaround to disable the sandbox for Linux builds.
https://github.com/electron-userland/electron-builder/issues/3872

**Comment by probonopd** [comment]
Yes, it would be good if users trying to run an AppImage would not need to do extra manual steps.

**Comment by Autre31415** [comment]
As others have ended up doing I've downgraded to electron v4 to account for this appimage problem until the posted electron-builder issue gets solved. Give [0.5.2](https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases/tag/v0.5.2) a shot and let me know if there's anymore problems with starting up the appimage on linux.
