### ISSUE TITLE
Saving error: 'Glyph Studio Project File' option does not result in right kind of file

### ISSUE THREAD

**Issue by raoulunger** [glyphr-studio/Glyphr-Studio-Desktop#76]
Hi,

I'm having great fun test driving Glyphr, and I think it's excellent, so thank you!! I tested both the web version and the desktop version on a Mac.

In both versions there are three options for saving the file (Glyphr Studio Project File, OTF, and SVG). According to the (again outstanding) help documentation the first option (GSPF) should result in a .txt file being saved. This is indeed true for the webversion. However, in de desktop version choosing the GSFP results in an OTF file. A .txt file is not produced.

Is this an error or intentional? If intentional it would perhaps be good to mention the difference in behaviour in the documentation.

Cheers!

**Comment by raoulunger** [comment]
'Closed as completed' - does this mean the issue is solved?

**Comment by Autre31415** [comment]
> 'Closed as completed' - does this mean the issue is solved?

Yep, this is addressed in https://github.com/glyphr-studio/Glyphr-Studio-Desktop/releases/tag/v0.6.0
