### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by mattlag** [glyphr-studio/Glyphr-Studio-Desktop#9]
Received an email from a user trying to install - they sent me the attached npm log.

[npm-debug.txt](https://github.com/glyphr-studio/Glyphr-Studio-Desktop/files/445545/npm-debug.txt)

**Comment by kethinov** [comment]
The build scripts presume a bash environment. Can you ask what happens if he tries it in Cygwin? We do our builds from OS X.

**Comment by mattlag** [comment]
They said they resolved the issue:

> I'm using Win10.  But I believe I resolved my issue by reinstalling bower.
> I now have the app running.  Will continue using it and let you know how it goes.
> Thanks for your quick reply.
